### PR TITLE
fix: unhandle error

### PR DESCRIPTION
**Pull request by awronski**
Try/Catch was added to handle errors. Previously when error
happened the whole application stopped working.

For example ```adsbygoogle.push() error: Fluid responsive ads must be at least 250px wide``` blow whole nuxt application.

### CODE REVIEW

**Comment by awronski** [comment]
@pi0 Could you look at it? I would like to push it to production if it is ok for you. Thanks!

**Comment by awronski** [comment]
@tmorehouse @pi0 Could you Guys publish it to npm?

Thanks and Happy New Year!

**Comment by awronski** [comment]
@pi0 any chance for merge? I am not sure if @tmorehouse is maitaining this repo any more?

**Comment by awronski** [comment]
@pi0 ping

**Comment by pi0** [comment]
@awronski Really sorry for the delay. Actually @tmorehouse is on a vacation right now. Will publish new release now.

**Pull request merged**
