### PR TITLE
fix: page level ads error

### LINKED ISSUE #56: "adsbygoogle.push() error: Only one 'enable_page_level_ads' allowed per page."
I have use google-adsense-module in my nuxt project.
But ads don't display and an error appears.
Anything to fix the problem?

Screenshot_1

### PR DESCRIPTION
**Pull request by farnabaz**
resolves #56

### CODE REVIEW

**Comment by farnabaz** [comment]
@otezz Do you mind try this PR and confirm if these changes fix the issue?

**Comment by otezz** [comment]
image

Hi @farnabaz, thank you for your effort. Unfortunately the issue is still there.

**Comment by leafkit** [comment]
Hi @farnabaz 

I was having the same issue. This PR fixed the issue for me, however this is not in the latest commit unless I'm missing something? I had to update the files manually to reflect this change.

**Comment by engelrolling** [comment]
Hi @farnabaz 

I tried aswell and still have the issue, exactly like in @otezz 's screenshot.

**Comment by leafkit** [comment]
Hi @farnabaz 

I'm getting the same errors as @otezz and @engelrolling

**Review by narendra087 — APPROVED** [review]
when will this update be released?

**Comment by aivchen** [comment]
>Hi @farnabaz, thank you for your effort. Unfortunately the issue is still there.

It's another issue. I believe you just don't have `<ins>` elements on the page.

@farnabaz, the initial issue is solved!

**Pull request merged**
